### ISSUE TITLE
Document the options

### ISSUE THREAD

**Issue by crazy4groovy** [kettanaito/page-with#1]
## Description

Would be great to document all the options:

[line](https://github.com/kettanaito/page-with/blob/main/src/pageWith.ts#L38)
`const { example, markup, contentBase, title } = options`

Cool lib!

**Comment by kettanaito** [comment]
Hey, @crazy4groovy. Thank you for the feedback! I've [documented the current options](https://github.com/kettanaito/page-with#options) in the readme. That should be enough.
